//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionRequest) DeepCopyInto(out *EvictionRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionRequest.
func (in *EvictionRequest) DeepCopy() *EvictionRequest {
	if in == nil {
		return nil
	}
	out := new(EvictionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvictionRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionRequestList) DeepCopyInto(out *EvictionRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EvictionRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionRequestList.
func (in *EvictionRequestList) DeepCopy() *EvictionRequestList {
	if in == nil {
		return nil
	}
	out := new(EvictionRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvictionRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionRequestSpec) DeepCopyInto(out *EvictionRequestSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.Requesters != nil {
		in, out := &in.Requesters, &out.Requesters
		*out = make([]Requester, len(*in))
		copy(*out, *in)
	}
	if in.Interceptors != nil {
		in, out := &in.Interceptors, &out.Interceptors
		*out = make([]Interceptor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HeartbeatDeadlineSeconds != nil {
		in, out := &in.HeartbeatDeadlineSeconds, &out.HeartbeatDeadlineSeconds
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionRequestSpec.
func (in *EvictionRequestSpec) DeepCopy() *EvictionRequestSpec {
	if in == nil {
		return nil
	}
	out := new(EvictionRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionRequestStatus) DeepCopyInto(out *EvictionRequestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActiveInterceptorClass != nil {
		in, out := &in.ActiveInterceptorClass, &out.ActiveInterceptorClass
		*out = new(string)
		**out = **in
	}
	if in.HeartbeatTime != nil {
		in, out := &in.HeartbeatTime, &out.HeartbeatTime
		*out = (*in).DeepCopy()
	}
	if in.ExpectedInterceptorFinishTime != nil {
		in, out := &in.ExpectedInterceptorFinishTime, &out.ExpectedInterceptorFinishTime
		*out = (*in).DeepCopy()
	}
	if in.PodEvictionStatus != nil {
		in, out := &in.PodEvictionStatus, &out.PodEvictionStatus
		*out = new(PodEvictionStatus)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionRequestStatus.
func (in *EvictionRequestStatus) DeepCopy() *EvictionRequestStatus {
	if in == nil {
		return nil
	}
	out := new(EvictionRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionTarget) DeepCopyInto(out *EvictionTarget) {
	*out = *in
	if in.PodRef != nil {
		in, out := &in.PodRef, &out.PodRef
		*out = new(LocalPodReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionTarget.
func (in *EvictionTarget) DeepCopy() *EvictionTarget {
	if in == nil {
		return nil
	}
	out := new(EvictionTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Interceptor) DeepCopyInto(out *Interceptor) {
	*out = *in
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Interceptor.
func (in *Interceptor) DeepCopy() *Interceptor {
	if in == nil {
		return nil
	}
	out := new(Interceptor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalPodReference) DeepCopyInto(out *LocalPodReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalPodReference.
func (in *LocalPodReference) DeepCopy() *LocalPodReference {
	if in == nil {
		return nil
	}
	out := new(LocalPodReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodEvictionStatus) DeepCopyInto(out *PodEvictionStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodEvictionStatus.
func (in *PodEvictionStatus) DeepCopy() *PodEvictionStatus {
	if in == nil {
		return nil
	}
	out := new(PodEvictionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Requester) DeepCopyInto(out *Requester) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Requester.
func (in *Requester) DeepCopy() *Requester {
	if in == nil {
		return nil
	}
	out := new(Requester)
	in.DeepCopyInto(out)
	return out
}
